package io.github.smithjustinn.theme

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

@Immutable
data class AppColors(
    val primary: Color,
    val onPrimary: Color,
    val primaryContainer: Color,
    val onPrimaryContainer: Color,
    val secondary: Color,
    val onSecondary: Color,
    val secondaryContainer: Color,
    val onSecondaryContainer: Color,
    val tertiary: Color,
    val onTertiary: Color,
    val tertiaryContainer: Color,
    val onTertiaryContainer: Color,
    val error: Color,
    val onError: Color,
    val errorContainer: Color,
    val onErrorContainer: Color,
    val background: Color,
    val onBackground: Color,
    val surface: Color,
    val onSurface: Color,
    val surfaceVariant: Color,
    val onSurfaceVariant: Color,
    val outline: Color,
    val outlineVariant: Color,
    val scrim: Color,
    val inverseSurface: Color,
    val inverseOnSurface: Color,
    val inversePrimary: Color,
    val surfaceDim: Color,
    val surfaceBright: Color,
    val surfaceContainerLowest: Color,
    val surfaceContainerLow: Color,
    val surfaceContainer: Color,
    val surfaceContainerHigh: Color,
    val surfaceContainerHighest: Color,
    // Custom Gameplay Colors
    val tacticalRed: Color,
    val goldenYellow: Color,
    val heartRed: Color,
    val diamondBlue: Color,
    val bonusGreen: Color,
    val heatGlowPrimary: Color,
    val startBackgroundTop: Color,
    val startBackgroundBottom: Color,
    val softBlue: Color,
    val darkBlue: Color,
    val inactiveBackground: Color,
    val heatBackgroundTop: Color,
    val heatBackgroundBottom: Color,
)

internal val LightAppColors =
    AppColors(
        primary = GoldenYellow, // Gold Primary
        onPrimary = Color.Black,
        primaryContainer = PrimaryContainerLight,
        onPrimaryContainer = OnPrimaryContainerLight,
        secondary = SecondaryLight,
        onSecondary = OnSecondaryLight,
        secondaryContainer = SecondaryContainerLight,
        onSecondaryContainer = OnSecondaryContainerLight,
        tertiary = TertiaryLight,
        onTertiary = OnTertiaryLight,
        tertiaryContainer = TertiaryContainerLight,
        onTertiaryContainer = OnTertiaryContainerLight,
        error = ErrorLight,
        onError = OnErrorLight,
        errorContainer = ErrorContainerLight,
        onErrorContainer = OnErrorContainerLight,
        background = Color(0xFF35654d), // Felt Green
        onBackground = Color.White,
        surface = SurfaceLight,
        onSurface = OnSurfaceLight,
        surfaceVariant = SurfaceVariantLight,
        onSurfaceVariant = OnSurfaceVariantLight,
        outline = OutlineLight,
        outlineVariant = OutlineVariantLight,
        scrim = ScrimLight,
        inverseSurface = InverseSurfaceLight,
        inverseOnSurface = InverseOnSurfaceLight,
        inversePrimary = InversePrimaryLight,
        surfaceDim = SurfaceDimLight,
        surfaceBright = SurfaceBrightLight,
        surfaceContainerLowest = SurfaceContainerLowestLight,
        surfaceContainerLow = SurfaceContainerLowLight,
        surfaceContainer = SurfaceContainerLight,
        surfaceContainerHigh = SurfaceContainerHighLight,
        surfaceContainerHighest = SurfaceContainerHighestLight,
        tacticalRed = Color(0xFFB91C1C), // Casino Red
        goldenYellow = GoldenYellow,
        heartRed = HeartRed,
        diamondBlue = DiamondBlue,
        bonusGreen = BonusGreen,
        heatGlowPrimary = HeatGlowPrimary,
        startBackgroundTop = Color(0xFF35654d),
        startBackgroundBottom = Color(0xFF1e3a2f),
        softBlue = SoftBlue,
        darkBlue = DarkBlue,
        inactiveBackground = Color(0x99000000), // Dark translucent
        heatBackgroundTop = HeatBackgroundTop,
        heatBackgroundBottom = HeatBackgroundBottom,
    )

internal val DarkAppColors =
    AppColors(
        primary = PrimaryDark,
        onPrimary = OnPrimaryDark,
        primaryContainer = PrimaryContainerDark,
        onPrimaryContainer = OnPrimaryContainerDark,
        secondary = SecondaryDark,
        onSecondary = OnSecondaryDark,
        secondaryContainer = SecondaryContainerDark,
        onSecondaryContainer = OnSecondaryContainerDark,
        tertiary = TertiaryDark,
        onTertiary = OnTertiaryDark,
        tertiaryContainer = TertiaryContainerDark,
        onTertiaryContainer = OnTertiaryContainerDark,
        error = ErrorDark,
        onError = OnErrorDark,
        errorContainer = ErrorContainerDark,
        onErrorContainer = OnErrorContainerDark,
        background = BackgroundDark,
        onBackground = OnBackgroundDark,
        surface = SurfaceDark,
        onSurface = OnSurfaceDark,
        surfaceVariant = SurfaceVariantDark,
        onSurfaceVariant = OnSurfaceVariantDark,
        outline = OutlineDark,
        outlineVariant = OutlineVariantDark,
        scrim = ScrimDark,
        inverseSurface = InverseSurfaceDark,
        inverseOnSurface = InverseOnSurfaceDark,
        inversePrimary = InversePrimaryDark,
        surfaceDim = SurfaceDimDark,
        surfaceBright = SurfaceBrightDark,
        surfaceContainerLowest = SurfaceContainerLowestDark,
        surfaceContainerLow = SurfaceContainerLowDark,
        surfaceContainer = SurfaceContainerDark,
        surfaceContainerHigh = SurfaceContainerHighDark,
        surfaceContainerHighest = SurfaceContainerHighestDark,
        tacticalRed = TacticalRed,
        goldenYellow = GoldenYellow,
        heartRed = HeartRed,
        diamondBlue = DiamondBlue,
        bonusGreen = BonusGreen,
        heatGlowPrimary = HeatGlowPrimary,
        startBackgroundTop = StartBackgroundTop,
        startBackgroundBottom = StartBackgroundBottom,
        softBlue = SoftBlue,
        darkBlue = DarkBlue,
        inactiveBackground = InactiveBackground,
        heatBackgroundTop = HeatBackgroundTop,
        heatBackgroundBottom = HeatBackgroundBottom,
    )
